# How to convert np.array to bytes

In [1]:
import numpy as np
import binascii

np.random.seed(0)

data = np.random.rand(3) # make random np.float64 array
print(data)
print(type(data[0]))
print(len(data))

[0.5488135  0.71518937 0.60276338]
<class 'numpy.float64'>
3


In [2]:
bytes_data = data.tobytes() # np.array(np.float64) to bytes
print(bytes_data)
print(type(bytes_data))
print(len(bytes_data))
print(bytes_data[0])
print(bytes_data[1])
print(type(bytes_data[0]))

b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?'
<class 'bytes'>
24
168
18
<class 'int'>


In [3]:
[x for x in bytes_data]

[168,
 18,
 95,
 86,
 225,
 143,
 225,
 63,
 51,
 135,
 96,
 207,
 212,
 226,
 230,
 63,
 75,
 137,
 110,
 107,
 214,
 73,
 227,
 63]

# How to convert bytes data to hexadecimal string

In [4]:
hex_str = bytes_data.hex()
print(hex_str)
print(type(hex_str))

a8125f56e18fe13f338760cfd4e2e63f4b896e6bd649e33f
<class 'str'>


In [5]:
hex_str2 = '0x' + hex_str
print(hex_str2)

0xa8125f56e18fe13f338760cfd4e2e63f4b896e6bd649e33f


In [6]:
print(bytes_data)
print(binascii.hexlify(bytes_data))
print(type(binascii.hexlify(bytes_data))) #bytes class but data looks like hex_str
print(binascii.hexlify(bytes_data).decode(encoding='ascii')) #construct a str from bytes interpreting them like ascii code
print(type(binascii.hexlify(bytes_data).decode(encoding='ascii')))

b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?'
b'a8125f56e18fe13f338760cfd4e2e63f4b896e6bd649e33f'
<class 'bytes'>
a8125f56e18fe13f338760cfd4e2e63f4b896e6bd649e33f
<class 'str'>


# How to convert hexadecimal string to bytes

In [7]:
#bytearray : return an object of bytes, the bytearray object is mutable
bytearray.fromhex(hex_str)

bytearray(b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?')

In [8]:
#bytes : return bytes of object, the bytes object is immutable
bytes.fromhex(hex_str)

b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?'

In [9]:
binascii.unhexlify(hex_str)

b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?'

In [10]:
bytearray.fromhex(binascii.hexlify(bytes_data).decode(encoding='ascii'))

bytearray(b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?')

In [11]:
bytes.fromhex(binascii.hexlify(bytes_data).decode(encoding='ascii'))

b'\xa8\x12_V\xe1\x8f\xe1?3\x87`\xcf\xd4\xe2\xe6?K\x89nk\xd6I\xe3?'

# How to convert bytes to np.array

In [12]:
print(type(bytes_data))
recon_data = np.frombuffer(bytes_data, np.float64)
print(recon_data)

<class 'bytes'>
[0.5488135  0.71518937 0.60276338]


In [13]:
recon_data = np.frombuffer(bytes.fromhex(binascii.hexlify(bytes_data).decode(encoding='ascii')), np.float64)
print(recon_data)

[0.5488135  0.71518937 0.60276338]


In [14]:
print(type(bytearray.fromhex(hex_str)))
recon_data = np.frombuffer(bytearray.fromhex(hex_str), np.float64)
print(recon_data)

<class 'bytearray'>
[0.5488135  0.71518937 0.60276338]


In [15]:
print(type(bytes.fromhex(hex_str)))
recon_data = np.frombuffer(bytes.fromhex(hex_str), np.float64)
print(recon_data)

<class 'bytes'>
[0.5488135  0.71518937 0.60276338]


In [16]:
recon_data = np.frombuffer(bytearray.fromhex(hex_str2), np.float64)
print(recon_data)

ValueError: non-hexadecimal number found in fromhex() arg at position 1

In [17]:
recon_data = np.frombuffer(bytearray.fromhex(hex_str2[2:]), np.float64) #should remove 0x in the hex string
print(recon_data)

[0.5488135  0.71518937 0.60276338]


# How to convert bytes to string

In [18]:
bytes_object = b"abc"
print(type(bytes_object))
bytes_to_str = bytes_object.decode(encoding='utf-8') # you should put the encoding your data is actually in
print(bytes_to_str)
print(type(bytes_to_str))

<class 'bytes'>
abc
<class 'str'>


In [19]:
bytes_object = b"abc"
print(type(bytes_object))
bytes_to_str = str(bytes_object,'utf-8')
print(bytes_to_str)
print(type(bytes_to_str))

<class 'bytes'>
abc
<class 'str'>


In [20]:
import timeit
print('bytes_object.decode() :' +  str(timeit.timeit(f'{bytes_object}.decode()', number=1000000)))
print('"".join(map(chr, bytes_object)) :' +  str(timeit.timeit(f'"".join(map(chr, {bytes_object}))', number=1000000)))
print('"".join([chr(_) for _ in bytes_object]) :' +  str(timeit.timeit(f'"".join([chr(_) for _ in {bytes_object}])', number=1000000)))

bytes_object.decode() :0.258908899999998
"".join(map(chr, bytes_object)) :1.1185924999999983
"".join([chr(_) for _ in bytes_object]) :1.252732199999997


# How to format a string of hex numbers

In [21]:
#positive number
a = 50
b = hex(a)
print(f'hex(a) : {b}')
print("f'0x{a:02x}' :"+ f'0x{a:02x}')
print("f'{a:x}' :" + f'{a:x}') #remove 0x
print("'%x'%a :"+ '%x'%a) #remove 0x
print("'{0:x}'.format(a) :" + '{0:x}'.format(a)) #remove 0x
print("format(a, 'x') :" + format(a, 'x')) #remove 0x
print("hex(a)[2:] :" + hex(a)[2:]) #remove 0x
print("hex(a).replace('x', '0') :" + hex(a).replace('x', '0'))

hex(a) : 0x32
f'0x{a:02x}' :0x32
f'{a:x}' :32
'%x'%a :32
'{0:x}'.format(a) :32
format(a, 'x') :32
hex(a)[2:] :32
hex(a).replace('x', '0') :0032


In [22]:
#negative number
a = -50
b = hex(a)
print(b)
print(f'0x{a:02x}')
print(f'{a:x}') #remove 0x
print('%x'%a) #remove 0x
print('{0:x}'.format(a)) #remove 0x
print(format(a, 'x')) #remove 0x
print(hex(a)[2:]) #failed to remove 0x
print(hex(a).replace('x', '0')) #leading '0's don't change the value of the number, so this string is mathematically correct

-0x32
0x-32
-32
-32
-32
-32
x32
-0032


In [23]:
int(hex(a).replace('x', '0'))

-32